version: '3'
<<<<<<< HEAD

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - docker-certs-client:/certs/client:ro
    networks:
      - jenkins-network

  dind:
    image: docker:19.03.12-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client
    networks:
      - jenkins-network

volumes:
  jenkins-data:
  docker-certs-client:

networks:
  jenkins-network:
=======
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  dind:
    image: docker:20.10-dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
>>>>>>> 1da5fbf (Updated Jenkinsfile with logging)
