version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - docker-certs-client:/certs/client:ro
    networks:
      - jenkins-network

  dind:
    image: docker:19.03.12-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client
    networks:
      - jenkins-network

volumes:
  jenkins-data:
  docker-certs-client:

networks:
  jenkins-network:
